import os
import uuid
import logging
from datetime import datetime

# Setup structured logger
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER
except ImportError:
    logger.error("reportlab is not installed.")
    raise ImportError("Please install reportlab: uv pip install reportlab")

from inference import InferenceResult


class ReportTemplate(SimpleDocTemplate):
    def __init__(self, filename, **kw):
        super().__init__(filename, **kw)
        self.report_id = "unknown"
        self.report_date = "unknown"
        self.report_time = "unknown"


def draw_header(canvas, doc):
    canvas.saveState()
    # Draw background box for header
    canvas.setFillColor(colors.HexColor("#E8F4FD"))
    # Header is at the top. A4 is 595.27 x 841.89 points
    canvas.rect(0, A4[1] - 1.5 * inch, A4[0], 1.5 * inch, stroke=0, fill=1)

    # Title
    canvas.setFillColor(colors.black)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(0.5 * inch, A4[1] - 0.75 * inch, "CortexRay")

    # Report info (right side)
    canvas.setFont("Helvetica", 10)
    canvas.drawRightString(A4[0] - 0.5 * inch, A4[1] - 0.5 * inch, f"Report ID: {doc.report_id}")
    canvas.drawRightString(A4[0] - 0.5 * inch, A4[1] - 0.7 * inch, f"Date: {doc.report_date}")
    canvas.drawRightString(A4[0] - 0.5 * inch, A4[1] - 0.9 * inch, f"Time: {doc.report_time}")

    # Line separator under header
    canvas.setStrokeColor(colors.gray)
    canvas.setLineWidth(1)
    canvas.line(0, A4[1] - 1.5 * inch, A4[0], A4[1] - 1.5 * inch)

    canvas.restoreState()


def draw_footer(canvas, doc):
    canvas.saveState()
    # Thin line above footer
    canvas.setStrokeColor(colors.gray)
    canvas.setLineWidth(0.5)
    canvas.line(0.5 * inch, 0.75 * inch, A4[0] - 0.5 * inch, 0.75 * inch)

    # Disclaimer
    canvas.setFont("Helvetica-Oblique", 8)
    disclaimer = "DISCLAIMER: This report is generated by an AI model and is for informational purposes only. It should not replace professional medical diagnosis."
    canvas.drawCentredString(A4[0] / 2.0, 0.6 * inch, disclaimer)

    # Footer text
    canvas.setFont("Helvetica", 9)
    canvas.drawString(0.5 * inch, 0.4 * inch, "Generated by CortexRay")
    canvas.drawRightString(A4[0] - 0.5 * inch, 0.4 * inch, f"Page {doc.page}")
    canvas.restoreState()


def create_report(filename, report_id, report_date, report_time):
    doc = ReportTemplate(
        filename,
        pagesize=A4,
        topMargin=1.7 * inch,
        bottomMargin=1.2 * inch,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
    )
    doc.report_id = report_id
    doc.report_date = report_date
    doc.report_time = report_time
    return doc


def build_pdf(doc, elements):
    def on_page(canvas, doc):
        draw_header(canvas, doc)
        draw_footer(canvas, doc)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)


def get_image_flowable(img_path, caption, style_normal):
    if not img_path or not os.path.exists(img_path):
        return [
            Table(
                [
                    [
                        Paragraph(
                            "<b>Image Not Available</b>",
                            ParagraphStyle("Centered", parent=style_normal, alignment=TA_CENTER),
                        )
                    ],
                ],
                colWidths=[200],
                rowHeights=[200],
                style=[
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOX", (0, 0), (-1, -1), 1, colors.lightgrey),
                    ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
                ],
            ),
            Spacer(1, 0.1 * inch),
            Paragraph(
                f"<i>{caption}</i>",
                ParagraphStyle("Centered", parent=style_normal, alignment=TA_CENTER),
            ),
        ]
    else:
        try:
            img = Image(img_path, width=200, height=200, kind="proportional")
            return [
                img,
                Spacer(1, 0.1 * inch),
                Paragraph(
                    f"<i>{caption}</i>",
                    ParagraphStyle("Centered", parent=style_normal, alignment=TA_CENTER),
                ),
            ]
        except Exception as e:
            logger.error(f"Error loading image {img_path}: {e}")
            return [
                Paragraph(
                    "<b>Error Loading Image</b>",
                    ParagraphStyle("Centered", parent=style_normal, alignment=TA_CENTER),
                )
            ]


def generate_report(
    patient: dict,
    scan: dict,
    inference_result,
    prognosis: dict = None,
    report_type: str = "fracture",
    output_dir: str = "reports/",
) -> str:
    """
    Generates a professional one-page clinical PDF report for bone fracture detection.
    """
    try:
        os.makedirs(output_dir, exist_ok=True)

        date_str = datetime.now().strftime("%Y%m%d")
        patient_name_safe = "".join(
            [c if c.isalnum() else "_" for c in patient.get("full_name", "Unknown")]
        )
        scan_id = scan.get("scan_id", "unknown")
        filename = f"{scan_id}_{patient_name_safe}_{date_str}.pdf"
        filepath = os.path.join(output_dir, filename).replace("\\", "/")

        report_id = str(uuid.uuid4())[:8].upper()
        report_date = datetime.now().strftime("%Y-%m-%d")
        report_time = datetime.now().strftime("%H:%M:%S")

        doc = create_report(filepath, report_id, report_date, report_time)
        elements = []

        styles = getSampleStyleSheet()
        style_h2 = ParagraphStyle(
            "H2",
            fontName="Helvetica-Bold",
            fontSize=12,
            spaceAfter=8,
            textTransform="uppercase",
            textColor=colors.HexColor("#333333"),
        )
        style_normal = styles["Normal"]
        style_normal.fontName = "Helvetica"

        # PATIENT INFORMATION
        elements.append(Paragraph("PATIENT INFORMATION", style_h2))
        patient_data = [
            [
                Paragraph(f"<b>Name:</b> {patient.get('full_name', 'N/A')}", style_normal),
                Paragraph(
                    f"<b>Comorbidities:</b> {', '.join(patient.get('comorbidities', [])) or 'None'}",
                    style_normal,
                ),
            ],
            [Paragraph(f"<b>Age:</b> {patient.get('age', 'N/A')}", style_normal), ""],
            [Paragraph(f"<b>Gender:</b> {patient.get('gender', 'N/A')}", style_normal), ""],
        ]
        t_patient = Table(patient_data, colWidths=[3.6 * inch, 3.6 * inch])
        t_patient.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        elements.append(t_patient)
        elements.append(Spacer(1, 0.2 * inch))

        # SCAN DETAILS
        elements.append(Paragraph("SCAN DETAILS", style_h2))
        scan_data = [
            [
                Paragraph(f"<b>Scan ID:</b> {scan.get('scan_id', 'N/A')}", style_normal),
                Paragraph(
                    f"<b>Upload Timestamp:</b> {scan.get('upload_timestamp', 'N/A')}", style_normal
                ),
            ],
            [
                Paragraph(
                    f"<b>Model Version:</b> {getattr(inference_result, 'model_version', 'N/A')}",
                    style_normal,
                ),
                "",
            ],
        ]
        t_scan = Table(scan_data, colWidths=[3.6 * inch, 3.6 * inch])
        t_scan.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        elements.append(t_scan)
        elements.append(Spacer(1, 0.2 * inch))

        # IMAGES
        img_orig = get_image_flowable(
            scan.get("original_file_path"), "Original X-ray", style_normal
        )

        # Only show heatmap if confidence is not inconclusive
        show_heatmap = (
            getattr(inference_result, "confidence_flag", "inconclusive") != "inconclusive"
        )
        img_heatmap = get_image_flowable(
            getattr(inference_result, "heatmap_path", None) if show_heatmap else None,
            "Heatmap",
            style_normal,
        )

        t_images = Table([[img_orig, img_heatmap]], colWidths=[3.6 * inch, 3.6 * inch])
        t_images.setStyle(
            TableStyle(
                [
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        elements.append(t_images)
        elements.append(Spacer(1, 0.3 * inch))

        # AI PREDICTION
        elements.append(Paragraph("AI PREDICTION", style_h2))

        flag = getattr(inference_result, "confidence_flag", "inconclusive")
        flag_colors = {
            "clear": "#4CAF50",  # green
            "low_confidence": "#FFC107",  # amber
            "inconclusive": "#F44336",  # red
        }
        bg_color = flag_colors.get(flag, "#9E9E9E")

        badge = Table(
            [
                [
                    Paragraph(
                        f"<font color='white'><b>{flag.replace('_', ' ').upper()}</b></font>",
                        ParagraphStyle("Centered", parent=style_normal, alignment=TA_CENTER),
                    )
                ]
            ],
            colWidths=[1.5 * inch],
            rowHeights=[0.25 * inch],
            style=[
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(bg_color)),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(bg_color)),
            ],
        )

        if report_type == "fracture":
            fracture_det = getattr(inference_result, "fracture_detected", False)
            fracture_color = "red" if fracture_det else "green"
            fracture_text = f"<font color='{fracture_color}'><b>{'DETECTED' if fracture_det else 'NOT DETECTED'}</b></font>"

            bone_reg = getattr(inference_result, "bone_region", "N/A")
            if flag == "inconclusive":
                bone_reg = "N/A"

            pred_data = [
                [
                    Paragraph(f"<b>Fracture:</b> {fracture_text}", style_normal),
                    Paragraph(
                        f"<b>Confidence:</b> {getattr(inference_result, 'fracture_confidence', 0.0):.1f}%",
                        style_normal,
                    ),
                ],
                [Paragraph(f"<b>Body Region:</b> {bone_reg.capitalize()}", style_normal), badge],
                [
                    Paragraph(
                        f"<b>Message:</b> {getattr(inference_result, 'message', '')}", style_normal
                    ),
                    "",
                ],
            ]
        else:
            # Arthritis specific prediction data
            grade = getattr(inference_result, "grade", "N/A")
            grade_name = getattr(inference_result, "grade_name", "N/A")

            pred_data = [
                [
                    Paragraph(f"<b>Arthritis Grade:</b> {grade} ({grade_name})", style_normal),
                    Paragraph(
                        f"<b>Confidence:</b> {getattr(inference_result, 'confidence', 0.0):.1f}%",
                        style_normal,
                    ),
                ],
                [Paragraph("", style_normal), badge],
                [
                    Paragraph(
                        f"<b>Message:</b> {getattr(inference_result, 'message', '')}", style_normal
                    ),
                    "",
                ],
            ]

        t_pred = Table(pred_data, colWidths=[3.6 * inch, 3.6 * inch])
        t_pred.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("SPAN", (0, 2), (1, 2)),  # Message spans both columns
                ]
            )
        )
        elements.append(t_pred)
        elements.append(Spacer(1, 0.2 * inch))

        # CLINICAL PROGNOSIS
        elements.append(Paragraph("CLINICAL PROGNOSIS", style_h2))
        if flag == "clear":
            if report_type == "fracture" and prognosis:
                ref_flag = prognosis.get("referral_flag", False)
                ref_color = "red" if ref_flag else "green"
                ref_text = f"<font color='{ref_color}'><b>{'YES - Orthopedic Consult Required' if ref_flag else 'NO'}</b></font>"

                prog_data = [
                    [
                        Paragraph("<b>Rest Duration:</b>", style_normal),
                        Paragraph(
                            f"{prognosis.get('rest_weeks_min', 'N/A')}-{prognosis.get('rest_weeks_max', 'N/A')} weeks",
                            style_normal,
                        ),
                    ],
                    [
                        Paragraph("<b>Immobilisation:</b>", style_normal),
                        Paragraph(
                            f"{prognosis.get('cast_type', 'N/A')} (Plaster: {'Yes' if prognosis.get('plaster_required') else 'No'})",
                            style_normal,
                        ),
                    ],
                    [
                        Paragraph("<b>Weight Bearing:</b>", style_normal),
                        Paragraph(str(prognosis.get("weight_bearing_status", "N/A")), style_normal),
                    ],
                    [
                        Paragraph("<b>Referral Required:</b>", style_normal),
                        Paragraph(ref_text, style_normal),
                    ],
                ]
            else:
                prog_data = [
                    [
                        Paragraph("<b>Clinical Recommendation:</b>", style_normal),
                        Paragraph(getattr(inference_result, "clinical_recommendation", "N/A"), style_normal)
                    ]
                ]

            t_prog = Table(prog_data, colWidths=[2.0 * inch, 5.2 * inch])
            t_prog.setStyle(
                TableStyle(
                    [
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                    ]
                )
            )
            elements.append(t_prog)
        else:
            elements.append(
                Paragraph(
                    "<i>Prognosis is unavailable for low confidence or inconclusive results. Please conduct a manual review.</i>",
                    style_normal,
                )
            )

        build_pdf(doc, elements)
        logger.info(f"Successfully generated report at {filepath}")
        return filepath
    except Exception as e:
        logger.error(f"Failed to generate report: {e}", exc_info=True)
        return ""


if __name__ == "__main__":
    from inference import InferenceResult

    dummy_patient = {
        "full_name": "Jane Doe",
        "age": 45,
        "gender": "Female",
        "comorbidities": ["Osteoporosis", "Type 2 Diabetes"],
    }

    dummy_scan = {
        "scan_id": "SCN-2023-9988",
        "upload_timestamp": "2023-10-27 14:32:00",
        "original_file_path": "tests/dummy_xray.jpg",
        "bone_affected": "hand",
    }

    dummy_inference_result = InferenceResult(
        fracture_detected=True,
        fracture_confidence=95.4,
        bone_region="hand",
        bone_confidence=99.1,
        confidence_flag="clear",
        heatmap_path="tests/dummy_heatmap.jpg",
        model_version="ResNet50-DualHead-v2.1",
        prediction_time_ms=120.5,
        message="High confidence fracture detected in the hand region.",
    )

    dummy_prognosis = {
        "rest_weeks_min": 4,
        "rest_weeks_max": 6,
        "cast_type": "Short arm cast",
        "plaster_required": True,
        "weight_bearing_status": "Non-weight bearing",
        "referral_flag": True,
    }

    logger.info("Generating test report with 'clear' confidence...")
    report_path1 = generate_report(
        dummy_patient, dummy_scan, dummy_inference_result, dummy_prognosis
    )

    dummy_inference_result_inconclusive = InferenceResult(
        fracture_detected=False,
        fracture_confidence=60.2,
        bone_region="unknown",
        bone_confidence=40.5,
        confidence_flag="inconclusive",
        heatmap_path="",
        model_version="ResNet50-DualHead-v2.1",
        prediction_time_ms=115.2,
        message="Model is inconclusive. Manual review required.",
    )

    dummy_scan_inconclusive = dummy_scan.copy()
    dummy_scan_inconclusive["scan_id"] = "SCN-2023-9989"

    logger.info("Generating test report with 'inconclusive' confidence...")
    report_path2 = generate_report(
        dummy_patient, dummy_scan_inconclusive, dummy_inference_result_inconclusive, dummy_prognosis
    )
